name: Android

on: workflow_dispatch

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build 
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
      
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/Android/Android.apk
